name: CI for Assignment2 (Gauss Solver)

on:
  push:
    paths:
      - 'Assignment2/**'
  pull_request:
    paths:
      - 'Assignment2/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev build-essential cmake
        
    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Build and test
      working-directory: ./Assignment2
      run: |
        make clean
        make
        make test
